// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/abtasty-search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/abtasty-search.get').default>>>>
    }
    '/api/features/apple-pay': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/features/apple-pay.get').default>>>>
    }
    '/api/image': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image.get').default>>>>
    }
    '/api/orders/:orderId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[orderId].get').default>>>>
    }
    '/api/orders/:orderId/status': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[orderId]/status.post').default>>>>
    }
    '/api/orders': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/index.post').default>>>>
    }
    '/api/products/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id].get').default>>>>
    }
    '/api/products/brand/:brand': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/brand/[brand].get').default>>>>
    }
    '/api/products/brands': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/brands.get').default>>>>
    }
    '/api/products/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/categories.get').default>>>>
    }
    '/api/products/category/:category': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/category/[category].get').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.get').default>>>>
    }
    '/api/products/paged': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/paged.get').default>>>>
    }
    '/api/products/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/search.get').default>>>>
    }
    '/api/receipt/:publicId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/receipt/[publicId].get').default>>>>
    }
    '/api/reco-search-results': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reco-search-results.post').default>>>>
    }
    '/api/reco': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reco.post').default>>>>
    }
    '/api/recommendations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/recommendations.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/recommendations.post').default>>>>
    }
    '/api/trial/select': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trial/select.post').default>>>>
    }
    '/api/valentines-products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/valentines-products.get').default>>>>
    }
    '/api/vendors': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vendors.get').default>>>>
    }
    '/v/:companyId/api/receipt/:publicId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v/[companyId]/api/receipt/[publicId].get').default>>>>
    }
    '/v/companyId/:companyId/api/receipt/:publicId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v/companyId/[companyId]/api/receipt/[publicId].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}